"""Add photo_path to employee

Revision ID: f63e69b0325c
Revises: 073784488099
Create Date: 2026-06-02 09:49:09.521227

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f63e69b0325c"
down_revision: Union[str, Sequence[str], None] = "073784488099"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("employee", sa.Column("photo_path", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("employee", "photo_path")
    # ### end Alembic commands ###
