version: '3.8'

services:
  db:
    image: postgres:14-alpine
    container_name: employee_db
    restart: always
    env_file:
      - ../.env
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
