name: ABZ.agency CI

on:
  push:
    branches: ["main"]
    paths:
      - 'ABZ.agency/**'
  pull_request:
    branches: ["main"]
    paths:
      - 'ABZ.agency/**'

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: "ABZ.agency/employee directory/services/backend"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install --no-root

      - name: Run pre-commit hooks
        run: poetry run pre-commit run --all-files
